// web/src/components/YybConfigModal.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import BaseButton from '@/components/ui/BaseButton.vue'
import BaseInput from '@/components/ui/BaseInput.vue'
import BaseSwitch from '@/components/ui/BaseSwitch.vue'
import { useYybLoginStore } from '@/stores/yyb-login'

const props = defineProps<{
  show: boolean
}>()

const emit = defineEmits(['close'])

const yybStore = useYybLoginStore()
const saving = ref(false)
const newOpenId = ref('')

const form = ref({
  apiToken: '',
  endpoint: 'http://211.154.25.123:28999/api/open/v1/farm/code',
  reconnectIntervalMinutes: 0,
  autoReconnect: true,
  openIds: [] as string[],
})

function resetForm() {
  const cfg = yybStore.config
  form.value = {
    apiToken: cfg.apiToken || '',
    endpoint: cfg.endpoint || 'http://211.154.25.123:28999/api/open/v1/farm/code',
    reconnectIntervalMinutes: cfg.reconnectIntervalMinutes || 0,
    autoReconnect: cfg.autoReconnect !== false,
    openIds: Array.isArray(cfg.openIds) ? [...cfg.openIds] : [],
  }
  newOpenId.value = ''
}

watch(() => props.show, (show) => {
  if (show) {
    yybStore.loadConfig().then(resetForm)
  }
})

const interval = computed({
  get: () => form.value.reconnectIntervalMinutes,
  set: (v: number) => {
    form.value.reconnectIntervalMinutes = Math.max(0, Number.isFinite(Number(v)) ? Number(v) : 0)
  },
})

function increaseInterval() {
  form.value.reconnectIntervalMinutes += 1
}

function decreaseInterval() {
  if (form.value.reconnectIntervalMinutes > 0) {
    form.value.reconnectIntervalMinutes -= 1
  }
}

function addOpenId() {
  const value = newOpenId.value.trim()
  if (!value)
    return
  if (!form.value.openIds.includes(value)) {
    form.value.openIds.push(value)
  }
  newOpenId.value = ''
}

function removeOpenId(index: number) {
  form.value.openIds.splice(index, 1)
}

function handleKeydown(event: KeyboardEvent) {
  if (event.key === 'Enter') {
    event.preventDefault()
    addOpenId()
  }
}

async function handleSave() {
  saving.value = true
  try {
    await yybStore.saveConfig({
      enabled: true,
      apiToken: form.value.apiToken,
      endpoint: form.value.endpoint,
      reconnectIntervalMinutes: form.value.reconnectIntervalMinutes,
      autoReconnect: form.value.autoReconnect,
      openIds: form.value.openIds,
    })
    emit('close')
  }
  finally {
    saving.value = false
  }
}

function close() {
  emit('close')
}
</script>

<template>
  <div v-if="show" class="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4" style="padding-bottom: max(1rem, env(safe-area-inset-bottom, 0))" @click.self="close">
    <div class="max-h-[min(85dvh,700px)] max-w-md w-full overflow-hidden rounded-2xl flex flex-col" :style="{ background: 'var(--theme-bg)', boxShadow: 'var(--theme-shadow-lg, 0 8px 32px rgba(0,0,0,0.16))' }">
      <div class="flex items-center justify-between p-4 shrink-0" style="border-bottom: 1px solid color-mix(in srgb, var(--theme-text) 10%, transparent)">
        <div>
          <h3 class="text-lg font-semibold" style="color: var(--theme-primary, var(--theme-text))">
            应用宝配置
          </h3>
          <p class="mt-1 text-xs opacity-70" style="color: var(--theme-text)">
            配置应用宝一键登录的 API Token 和 OpenID
          </p>
        </div>
        <BaseButton variant="ghost" class="!p-1" @click="close">
          <div class="i-carbon-close text-xl" :style="{ color: 'var(--theme-text)' }" />
        </BaseButton>
      </div>

      <div class="flex-1 overflow-y-auto p-4 space-y-4">
        <BaseInput
          v-model="form.apiToken"
          label="API Token"
          type="password"
          placeholder="请输入 API Token"
          class="farm-input"
        />

        <BaseInput
          v-model="form.endpoint"
          label="接口地址"
          placeholder="请输入接口地址"
          class="farm-input"
        />

        <div class="space-y-2">
          <label class="text-sm text-gray-700 font-medium dark:text-gray-300">
            运行中定时重连间隔（分钟）
          </label>
          <div class="flex items-center overflow-hidden border-3 border-black/10 rounded-xl bg-white dark:border-gray-600 dark:bg-gray-800">
            <button
              type="button"
              class="h-11 w-12 flex items-center justify-center text-lg font-bold transition hover:bg-gray-100 dark:hover:bg-gray-700"
              :style="{ color: 'var(--theme-text)' }"
              @click="decreaseInterval"
            >
              −
            </button>
            <input
              v-model.number="interval"
              type="number"
              min="0"
              class="h-11 min-w-0 flex-1 border-x-3 border-black/10 bg-transparent text-center outline-none dark:border-gray-600 dark:text-white"
            >
            <button
              type="button"
              class="h-11 w-12 flex items-center justify-center text-lg font-bold transition hover:bg-gray-100 dark:hover:bg-gray-700"
              :style="{ color: 'var(--theme-text)' }"
              @click="increaseInterval"
            >
              +
            </button>
          </div>
          <p class="text-xs text-gray-500 dark:text-gray-400">
            输入 0 则不进行定时重登；设置后到达间隔时间将自动重新获取 Code 并重登
          </p>
        </div>

        <div class="space-y-1">
          <BaseSwitch v-model="form.autoReconnect" label="离线后自动重连" />
          <p class="text-xs text-gray-500 dark:text-gray-400">
            账号被踢下线或断线后自动获取新 Code 并重登
          </p>
        </div>

        <div class="space-y-2">
          <label class="text-sm text-gray-700 font-medium dark:text-gray-300">
            OpenID 列表
          </label>
          <div class="space-y-2">
            <div
              v-for="(openid, index) in form.openIds"
              :key="openid"
              class="flex items-center justify-between gap-2 border border-gray-200 rounded-xl bg-gray-50 px-3 py-2 dark:border-gray-600 dark:bg-gray-800/50"
            >
              <span class="min-w-0 flex-1 truncate text-sm" :style="{ color: 'var(--theme-text)' }">
                {{ openid }}
              </span>
              <button
                type="button"
                class="text-gray-400 hover:text-red-500 dark:hover:text-red-400"
                @click="removeOpenId(index)"
              >
                <div class="i-carbon-trash-can text-lg" />
              </button>
            </div>
            <div class="flex gap-2">
              <BaseInput
                v-model="newOpenId"
                placeholder="输入新 OpenID"
                class="flex-1 farm-input"
                @keydown="handleKeydown"
              />
              <BaseButton variant="secondary" size="sm" class="shrink-0" @click="addOpenId">
                添加
              </BaseButton>
            </div>
          </div>
        </div>

      </div>

      <div class="flex justify-end gap-2 border-t p-4 shrink-0 dark:border-gray-700" style="border-top-color: color-mix(in srgb, var(--theme-text) 10%, transparent)">
        <BaseButton variant="outline" class="cartoon-btn" @click="close">
          取消
        </BaseButton>
        <BaseButton variant="primary" class="cartoon-btn" :loading="saving" @click="handleSave">
          保存
        </BaseButton>
      </div>
    </div>
  </div>
</template>

// frontend/src/components/YybConfigModal.tsx
import { useEffect, useState } from 'react';
import { ChevronDown, Eye, EyeOff, Trash2, X } from 'lucide-react';
import { useAppStore } from '@/store';
import type { YybConfig } from '@/types';

interface YybConfigModalProps {
  open: boolean;
  onClose: () => void;
}

export function YybConfigModal({ open, onClose }: YybConfigModalProps) {
  const { yybConfig, setYybConfig } = useAppStore();
  const [form, setForm] = useState<YybConfig>(yybConfig);
  const [showToken, setShowToken] = useState(false);
  const [showDocs, setShowDocs] = useState(false);
  const [newOpenId, setNewOpenId] = useState('');

  useEffect(() => {
    if (open) {
      setForm(yybConfig);
      document.body.style.overflow = 'hidden';
    } else {
      document.body.style.overflow = '';
    }
    return () => {
      document.body.style.overflow = '';
    };
  }, [open, yybConfig]);

  const handleSave = () => {
    setYybConfig(form);
    onClose();
  };

  const addOpenId = () => {
    const trimmed = newOpenId.trim();
    if (!trimmed) return;
    if (form.openIds.includes(trimmed)) {
      alert('OpenID 已存在');
      return;
    }
    setForm({ ...form, openIds: [...form.openIds, trimmed] });
    setNewOpenId('');
  };

  const removeOpenId = (id: string) => {
    setForm({ ...form, openIds: form.openIds.filter((item) => item !== id) });
  };

  if (!open) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/40 sm:items-center">
      <div className="relative flex h-[92vh] w-full max-w-md flex-col rounded-t-3xl bg-white sm:h-auto sm:max-h-[90vh] sm:rounded-3xl">
        <div className="flex items-center justify-between border-b border-gray-100 px-5 py-4">
          <div>
            <h2 className="text-lg font-bold text-[#4A90E2]">应用宝配置</h2>
            <p className="mt-0.5 text-xs text-gray-500">
              配置应用宝一键登录的 API Token 和 OpenID
            </p>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="rounded-full p-2 text-gray-500 transition-colors hover:bg-gray-100"
            aria-label="关闭"
          >
            <X size={20} />
          </button>
        </div>

        <div className="flex-1 overflow-y-auto px-5 py-4">
          <button
            type="button"
            onClick={() => setShowDocs(!showDocs)}
            className="flex w-full items-center justify-between rounded-xl bg-blue-50 px-4 py-3 text-[#4A90E2] transition-colors hover:bg-blue-100"
          >
            <span className="flex items-center gap-2 text-sm font-medium">
              <span>📖</span> 应用宝对接说明
            </span>
            <ChevronDown
              size={18}
              className={`transition-transform ${showDocs ? 'rotate-180' : ''}`}
            />
          </button>

          {showDocs && (
            <div className="mt-3 rounded-xl bg-gray-50 p-3 text-xs leading-relaxed text-gray-600">
              <p>1. 在下方输入从服务端获取的 API Token。</p>
              <p>2. 填写用于获取登录 Code 的接口地址。</p>
              <p>3. 添加需要自动获取 Code 的 OpenID。</p>
              <p>4. 保存后可在添加账号时选择“应用宝”登录方式。</p>
            </div>
          )}

          <div className="mt-5 space-y-5">
            <FormField label="API Token">
              <div className="relative">
                <input
                  type={showToken ? 'text' : 'password'}
                  value={form.apiToken}
                  onChange={(e) => setForm({ ...form, apiToken: e.target.value })}
                  placeholder="请输入 API Token"
                  className="w-full rounded-xl border border-gray-200 bg-white px-4 py-3 pr-11 text-sm text-gray-800 outline-none placeholder:text-gray-400 focus:border-blue-400"
                />
                <button
                  type="button"
                  onClick={() => setShowToken(!showToken)}
                  className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400"
                  aria-label={showToken ? '隐藏' : '显示'}
                >
                  {showToken ? <EyeOff size={18} /> : <Eye size={18} />}
                </button>
              </div>
            </FormField>

            <FormField label="接口地址">
              <input
                type="text"
                value={form.apiUrl}
                onChange={(e) => setForm({ ...form, apiUrl: e.target.value })}
                placeholder="http://..."
                className="w-full rounded-xl border border-gray-200 bg-white px-4 py-3 text-sm text-gray-800 outline-none placeholder:text-gray-400 focus:border-blue-400"
              />
            </FormField>

            <FormField label="运行中定时重连间隔（分钟）">
              <div className="flex items-center gap-3">
                <button
                  type="button"
                  onClick={() =>
                    setForm({ ...form, reconnectInterval: Math.max(0, form.reconnectInterval - 1) })
                  }
                  className="flex h-11 w-11 flex-shrink-0 items-center justify-center rounded-xl border border-gray-200 bg-white text-lg text-gray-600 transition-colors hover:bg-gray-50"
                >
                  −
                </button>
                <input
                  type="number"
                  value={form.reconnectInterval}
                  onChange={(e) =>
                    setForm({ ...form, reconnectInterval: Math.max(0, Number(e.target.value)) })
                  }
                  className="flex-1 rounded-xl border border-gray-200 bg-white px-4 py-3 text-center text-sm text-gray-800 outline-none focus:border-blue-400"
                />
                <button
                  type="button"
                  onClick={() => setForm({ ...form, reconnectInterval: form.reconnectInterval + 1 })}
                  className="flex h-11 w-11 flex-shrink-0 items-center justify-center rounded-xl border border-gray-200 bg-white text-lg text-gray-600 transition-colors hover:bg-gray-50"
                >
                  +
                </button>
              </div>
              <p className="mt-1.5 text-xs text-gray-400">
                输入 0 则不进行定时重登；设置后到达间隔时间将自动重新获取 Code 并重登
              </p>
            </FormField>

            <div className="flex items-center justify-between rounded-xl border border-gray-100 bg-white p-4">
              <div>
                <p className="text-sm font-medium text-gray-800">离线后自动重连</p>
                <p className="text-xs text-gray-500">账号被踢下线或断线后自动获取新 Code 并重登</p>
              </div>
              <button
                type="button"
                onClick={() => setForm({ ...form, autoReconnect: !form.autoReconnect })}
                className={`relative h-7 w-12 rounded-full transition-colors ${
                  form.autoReconnect ? 'bg-[#5A9A4A]' : 'bg-gray-300'
                }`}
                aria-label="切换自动重连"
              >
                <span
                  className={`absolute top-0.5 h-6 w-6 rounded-full bg-white shadow transition-transform ${
                    form.autoReconnect ? 'left-0.5 translate-x-5' : 'left-0.5'
                  }`}
                />
              </button>
            </div>

            <div className="space-y-2">
              <p className="text-sm font-medium text-gray-800">OpenID 列表</p>
              <div className="space-y-2">
                {form.openIds.map((id) => (
                  <div
                    key={id}
                    className="flex items-center justify-between rounded-xl border border-gray-200 bg-white px-3 py-2.5"
                  >
                    <span className="break-all pr-2 text-xs text-gray-700">{id}</span>
                    <button
                      type="button"
                      onClick={() => removeOpenId(id)}
                      className="flex-shrink-0 rounded-lg p-1.5 text-gray-400 transition-colors hover:bg-red-50 hover:text-red-500"
                      aria-label="删除"
                    >
                      <Trash2 size={18} />
                    </button>
                  </div>
                ))}
              </div>
              <div className="flex gap-2">
                <input
                  type="text"
                  value={newOpenId}
                  onChange={(e) => setNewOpenId(e.target.value)}
                  placeholder="输入新 OpenID"
                  className="flex-1 rounded-xl border border-gray-200 bg-white px-4 py-3 text-sm text-gray-800 outline-none placeholder:text-gray-400 focus:border-blue-400"
                  onKeyDown={(e) => e.key === 'Enter' && addOpenId()}
                />
                <button
                  type="button"
                  onClick={addOpenId}
                  className="rounded-xl border border-gray-200 bg-[#F5F5F5] px-4 py-2 text-sm font-medium text-gray-700 transition-colors hover:bg-gray-100"
                >
                  添加
                </button>
              </div>
            </div>
          </div>
        </div>

        <div className="flex items-center justify-end gap-3 border-t border-gray-100 px-5 py-4">
          <button
            type="button"
            onClick={onClose}
            className="rounded-full px-5 py-2 text-sm font-medium text-[#5A9A4A] transition-colors hover:bg-green-50"
          >
            取消
          </button>
          <button
            type="button"
            onClick={handleSave}
            className="rounded-full bg-[#4A90E2] px-6 py-2 text-sm font-medium text-white shadow-md shadow-blue-200 transition-colors hover:bg-[#3A80D2]"
          >
            保存
          </button>
        </div>
      </div>
    </div>
  );
}

function FormField({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div className="space-y-1.5">
      <label className="text-sm font-medium text-gray-700">{label}</label>
      {children}
    </div>
  );
}
